#!/bin/bash

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"

cd "$DIR"

git submodule update --init --recursive

for fname in "$DIR"/.*; do
    if [[ -f $fname ]]; then
        fname="$(basename "$fname")"
        ln -snf "$DIR/$fname" "$HOME/$fname"
    fi
done

# Bash-completion
set -x
mkdir -p "$HOME/.local/share/"
rm -f "$HOME/.local/share/bash-completion"
ln -sfn "$DIR/.local/share/bash-completion" "$HOME/.local/share/"

# For neovim
mkdir -p "$HOME"/.config
ln -sfn "$DIR"/vim "$HOME"/.config/nvim
ln -sfn "$DIR"/.vimrc "$HOME"/.config/nvim/init.vim

for d in "$DIR"/config/*; do
  ln -sfn "$d" "$HOME"/.config/"$(basename "$d")"
done
exit
mkdir -p "$HOME"/bin
ln -sfn "$DIR"/bin/* "$HOME"/bin/
rm -f "$HOME"/.vim
ln -sfn "$DIR"/vim "$HOME"/.vim

pip install neovim

echo "Installing bundles"
vim +BundleInstall! +qall
echo "Installing GO binaries"
vim +GoInstallBinaries +qall
vim +UpdateRemotePlugins +qall

echo "Done!"
