#!/bin/bash

set -eux
set -o pipefail

# Neovim pip
pip install --upgrade pip
pip install --upgrade neovim pynvim msgpack
gem install neovim && gem environment

# Go binaries
mkdir -p ~/gocode/src/github.com/
nvim +GoInstallBinaries +qall
