#!/bin/bash

set -eux
set -o pipefail

yarn_packages=(
  bash-language-server
  diagnostic-languageserver
  dockerfile-language-server-nodejs
  eslint
  jshint
  lua-fmt
  markdownlint
  neovim
  prettier
  prettier-plugin-toml
  pyright
  tern
  typescript
  typescript-language-server
)

pip_packages=(
  cmake-language-server
  msgpack
  neovim
  pip
  pynvim
)


# Python Packages
pip install --upgrade "${pip_packages[@]}"

# Ruby Gem deps
gem install neovim
gem environment

# Node Packages
npm install -g -f yarn
yarn global add --force --non-interactive "${yarn_packages[@]}"

# Go binaries
mkdir -p ~/gocode/src/github.com/
go install golang.org/x/tools/gopls@latest
go install github.com/mattn/efm-langserver@latest
nvim +GoInstallBinaries +qall
