alias:
  po: v1/pods

  crb: rbac.authorization.k8s.io/v1/clusterrolebindings

  cr: rbac.authorization.k8s.io/v1/clusterroles

  dep: apps/v1/deployments

  gr: source.toolkit.fluxcd.io/v1beta1/gitrepositories
  git: source.toolkit.fluxcd.io/v1beta1/gitrepositories
  gitrepository: source.toolkit.fluxcd.io/v1beta1/gitrepositories

  hc: source.toolkit.fluxcd.io/v1beta1/helmcharts
  helmchart: source.toolkit.fluxcd.io/v1beta1/helmcharts

  hr: helm.toolkit.fluxcd.io/v2beta1/helmreleases
  helmrelease: helm.toolkit.fluxcd.io/v2beta1/helmreleases

  ku: kustomize.toolkit.fluxcd.io/v1beta1/kustomizations
  kust: kustomize.toolkit.fluxcd.io/v1beta1/kustomizations
  kustomizations: kustomize.toolkit.fluxcd.io/v1beta1/kustomizations
